{{- $ctx := dict "helm" . }}
{{- $tenant := ternary "multitenant" "0" .Values.enableMultitenancy }}
{{- range $i, $zone := .Values.availabilityZones }}
{{- if $zone.vmagent.enabled }}
{{- if (($zone.vmagent).spec).remoteWrite }} 
  {{- fail "Error: distributed vmagent doesn't support customized remoteWrite address" }}
{{- end }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  labels: {{ include "victoria-metrics-distributed.labels" $ | nindent 4 }}
  {{- with $zone.vmagent.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end  }}
  {{- $_ := set $ctx "appKey" (list "availabilityZones" $i "vmagent") }}
  name: {{ include "vm.fullname" $ctx }}
  namespace: {{ include "vm.namespace" $ }}
{{- $spec := mergeOverwrite (deepCopy ($zone.common).spec) (deepCopy ($zone.vmagent).spec) }}
{{- $remoteWrites := default list }}
{{- range $rwZone := $.Values.availabilityZones }}
  {{- if $rwZone.write.allow }}
    {{- $url := trimSuffix "/" (include "vm.url" $ctx) }}
    {{- $remoteWrites = append $remoteWrites (dict "url" (printf "%s/insert/%s/prometheus/api/v1/write" $url $tenant)) }}
  {{- end }}
{{- end }}
{{- $_ := set $spec "remoteWrite" (concat $remoteWrites ($spec.remoteWrites | default list)) }}
spec: {{ toYaml $spec | nindent 2 }}
{{- end }}
{{- end }}
