{{- if .Values.serviceMonitor.enabled -}}
{{- $serviceMonitor := .Values.serviceMonitor -}}
{{- $ctx := dict "helm" . "extraLabels" $serviceMonitor.extraLabels }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  {{- with $serviceMonitor.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  labels: {{ include "chart.labels" $ctx | nindent 4 }}
  name: {{ include "vm.fullname" $ctx }}
  {{- with $serviceMonitor.namespace }}
  namespace: {{ . }}
  {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ include "vm.namespace" . }}
  selector:
    matchLabels: {{ include "chart.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      {{- with $serviceMonitor.basicAuth }}
      basicAuth: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $serviceMonitor.scheme }}
      scheme: {{ . }}
      {{- end }}
      {{- with $serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with $serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with $serviceMonitor.tlsConfig }}
      tlsConfig: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $serviceMonitor.relabelings }}
      relabelings: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $serviceMonitor.metricRelabelings }}
      metricRelabelings: {{ toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
