{{- $vpa := .Values.server.verticalPodAutoscaler }}
{{- if $vpa.enabled }}
{{- $ctx := dict "helm" . "appKey" "server" }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "vm.plain.fullname" $ctx }}
  namespace: {{ include "vm.namespace" . }}
spec:
  {{- with $vpa.recommenders }}
  recommenders: {{ toYaml . | nindent 4 }}
  {{- end }}
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "vm.plain.fullname" $ctx }}
  {{- with $vpa.updatePolicy }}
  updatePolicy: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with $vpa.resourcePolicy }}
  resourcePolicy: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
