{{- $app := .Values.alertmanager }}
{{- if and $app.enabled $app.templateFiles }}
{{- $ctx := dict "helm" . "extraLabels" (dict "app.kubernetes.io/component" (printf "%s-alertmanager" (include "vm.name" .))) }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "vm.fullname" . }}-alertmanager-extra-tpl
  namespace: {{ include "vm.namespace" . }}
  labels: {{ include "victoria-metrics-k8s-stack.labels" $ctx | nindent 4 }}
data:
{{- range $file, $template := $app.templateFiles }}
  {{ $file }}: |-
     {{- $template | nindent 4 }}
{{- end }}
{{- end }}
