{{- $app := .Values }}
{{- $ctx := dict "helm" . }}
{{- $ingresses := dict "" $app.ingress "internal" $app.ingressInternal }}
{{- range $suffix, $ingress := $ingresses }}
{{- if $ingress.enabled }}
{{- $_ := set $ctx "extraLabels" $ingress.extraLabels }}
{{- $serviceName := include "vm.fullname" $ctx }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- with $ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  labels: {{ include "chart.labels" $ctx | nindent 4 }}
  name: {{ $serviceName }}{{ ternary "" (printf "-%s" $suffix) (empty $suffix) }}
  namespace: {{ include "vm.namespace" $ctx }}
spec:
  {{- with $ingress.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with $ingress.tls }}
  tls: {{ tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  rules:
    {{- range $ingress.hosts }}
    - host: {{ tpl .name $ }}
      http:
        paths:
          - path: {{ .path }}
            {{- with $ingress.pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ $serviceName }}
                port: {{ include "vm.ingress.port" . | nindent 18 }}
    {{- end }}
{{- end }}
{{- end }}
