{{- if eq .Values.secretName "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vm.fullname" .}}
  namespace: {{ include "vm.namespace" . }}
  labels: {{ include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  auth.yml: |{{ toYaml .Values.config | b64enc | nindent 4 }}
{{- end }}
