{{- $app := .Values.server }}
{{- $service := $app.service }}
{{- if $app.enabled -}}
{{- $ctx := dict "helm" . "extraLabels" $service.labels "appKey" "server" }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "vm.namespace" . }}
  {{- with $service.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  labels: {{ include "victoria-logs.server.labels" $ctx | nindent 4 }}
  name: {{ include "vm.plain.fullname" $ctx }}
spec:
  {{- $clusterIP := $service.clusterIP }}
  {{- if and (not $clusterIP) $app.statefulSet.enabled }}
    {{- $clusterIP = "None" }}
  {{- end }}
  {{- with $clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with $service.externalIPs }}
  externalIPs: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with $service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with $service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- $type := $service.type }}
  {{- if and (not $type) $app.statefulSet.enabled }}
    {{- $type = "ClusterIP" }}
  {{- end }}
  type: {{ $type }}
  {{- with $service.healthCheckNodePort }}
  healthCheckNodePort: {{ . }}
  {{- end }}
  {{- with $service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with $service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with $service.ipFamilies }}
  ipFamilies: {{ toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: http
      port: {{ $service.servicePort }}
      protocol: TCP
      targetPort: http
      {{- with $service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector: {{ include "victoria-logs.server.matchLabels" (omit $ctx "extraLabels") | nindent 4 }}
{{- end }}
