{{- $app := .Values.server }}
{{- if $app.persistentVolume.enabled -}}
{{- if not $app.statefulSet.enabled -}}
{{- if not $app.persistentVolume.existingClaim -}}
{{- $ctx := dict "helm" . "appKey" "server" }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "vm.plain.fullname" $ctx }}
  namespace: {{ include "vm.namespace" . }}
  {{- with $app.persistentVolume.annotations  }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  labels: {{ include "victoria-logs.server.labels" . | nindent 4 }}
spec:
  {{- with $app.persistentVolume.accessModes }}
  accessModes: {{ toYaml . | nindent 4 }}
  {{- end }}
  resources:
    requests:
      storage: {{ $app.persistentVolume.size }}
  {{- with $app.persistentVolume.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  {{- with $app.persistentVolume.matchLabels }}
  selector:
    matchLabels: {{ toYaml . | nindent 6 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
