{{- $app := .Values.vminsert }}
{{- $service := $app.service }}
{{- if $app.enabled -}}
{{- $ctx := dict "helm" . "extraLabels" $service.labels "appKey" "vminsert" }}
apiVersion: v1
kind: Service
metadata:
  {{- with $service.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  labels: {{ include "victoria-metrics.vminsert.labels" $ctx | nindent 4 }}
  name: {{ include "vm.plain.fullname" $ctx }}
  namespace: {{ include "vm.namespace" $ctx }}
spec:
  {{- with $service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with $service.externalIPs }}
  externalIPs: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with $service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with $service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{ toYaml . | nindent 4 }}
  {{- end }}
  type: {{ $service.type }}
  {{- with $service.healthCheckNodePort }}
  healthCheckNodePort: {{ . }}
  {{- end }}
  {{- with $service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with $service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with $service.ipFamilies }}
  ipFamilies: {{ toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: http
      port: {{ $service.servicePort }}
      protocol: TCP
      targetPort: {{ $service.targetPort }}
    {{- range $service.extraPorts }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: TCP
      targetPort: {{ .targetPort }}
    {{- end }}
    {{- with $app.extraArgs.clusternativeListenAddr }}
    - name: cluster-tcp
      protocol: TCP
      port: {{ include "vm.port.from.flag" (dict "flag" .) }}
      targetPort: cluster-tcp
    {{- end }}
    {{- with $app.extraArgs.graphiteListenAddr }}
    - name: graphite-tcp
      protocol: TCP
      port: {{ include "vm.port.from.flag" (dict "flag" .) }}
      targetPort: graphite-tcp
    - name: graphite-udp
      protocol: UDP
      port: {{ include "vm.port.from.flag" (dict "flag" .) }}
      targetPort: graphite-udp
    {{- end }}
    {{- with $app.extraArgs.influxListenAddr }}
    - name: influx-tcp
      protocol: TCP
      port: {{ include "vm.port.from.flag" (dict "flag" .) }}
      targetPort: influx-tcp
    - name: influx-udp
      protocol: UDP
      port: {{ include "vm.port.from.flag" (dict "flag" .) }}
      targetPort: influx-udp
    {{- end }}
    {{- with $app.extraArgs.opentsdbHTTPListenAddr }}
    - name: opentsdbhttp
      port: {{ include "vm.port.from.flag" (dict "flag" .) }}
      targetPort: opentsdbhttp
    {{- end }}
    {{- with $app.extraArgs.opentsdbListenAddr }}
    {{- if or $service.udp (ne $service.type "LoadBalancer") }}
    - name: opentsdb-udp
      protocol: UDP
      port: {{ include "vm.port.from.flag" (dict "flag" .) }}
      targetPort: opentsdb-udp
    {{- end }}
    - name: opentsdb-tcp
      protocol: TCP
      port: {{ include "vm.port.from.flag" (dict "flag" .) }}
      targetPort: opentsdb-tcp
    {{- end }}
  selector: {{ include "victoria-metrics.vminsert.matchLabels" (omit $ctx "extraLabels") | nindent 4 }}
{{- end }}
