{{- $pdb := .Values.vmselect.podDisruptionBudget }}
{{- if $pdb.enabled }}
{{- $ctx := dict "helm" . "extraLabels" $pdb.labels "appKey" "vmselect" }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "vm.plain.fullname" $ctx }}
  namespace: {{ include "vm.namespace" . }}
  labels: {{ include "victoria-metrics.vmselect.labels" $ctx | nindent 4 }}
spec:
  {{- with $pdb.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with $pdb.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  selector:
    matchLabels: {{ include "victoria-metrics.vmselect.matchLabels" (omit $ctx "extraLabels") | nindent 6 }}
{{- end }}
