{{- $app := .Values.vmselect }}
{{- $service := $app.service }}
{{- if $app.enabled -}}
{{- $ctx := dict "helm" . "extraLabels" $service.labels "appKey" "vmselect" }}
apiVersion: v1
kind: Service
metadata:
  {{- with $service.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  labels: {{ include "victoria-metrics.vmselect.labels" $ctx | nindent 4 }}
  name: {{ include "vm.plain.fullname" $ctx }}
  namespace: {{ include "vm.namespace" . }}
spec:
  {{- $clusterIP := ternary "None" $service.clusterIP $app.statefulSet.enabled }}
  {{- with $clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- $externalIPs := ternary (default list) $service.externalIPs $app.statefulSet.enabled }}
  {{- with $externalIPs }}
  externalIPs: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- $loadBalancerIP := ternary "" $service.loadBalancerIP $app.statefulSet.enabled }}
  {{- with $loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- $loadBalancerSourceRanges := ternary (default list) $service.loadBalancerSourceRanges $app.statefulSet.enabled }}
  {{- with $loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{ toYaml . | nindent 4 }}
  {{- end }}
  type: {{ ternary "ClusterIP" $service.type $app.statefulSet.enabled }}
  {{- with $service.healthCheckNodePort }}
  healthCheckNodePort: {{ . }}
  {{- end }}
  {{- with $service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with $service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with $service.ipFamilies }}
  ipFamilies: {{ toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: http
      port: {{ $service.servicePort }}
      protocol: TCP
      targetPort: {{ $service.targetPort }}
    {{- range $service.extraPorts }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: TCP
      targetPort: {{ .targetPort }}
    {{- end }}
    {{- with $app.extraArgs.clusternativeListenAddr }}
    - name: cluster-tcp
      protocol: TCP
      port: {{ include "vm.port.from.flag" (dict "flag" .) }}
      targetPort: cluster-tcp
    {{- end }}
  selector: {{ include "victoria-metrics.vmselect.matchLabels" (omit $ctx "extraLabels") | nindent 4 }}
{{- end }}
