{{- $app := .Values.vmselect }}
{{- $ingress := $app.vmselect }}
{{- if and $app.enabled $ingress.enabled  }}
{{- $ctx := dict "helm" . "extraLabels" $ingress.extraLabels "appKey" "vmselect" }}
{{- $serviceName := include "vm.plain.fullname" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- with $ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  labels: {{ include "victoria-metrics.vmselect.labels" $ctx | nindent 4 }}
  name: {{ $serviceName }}
  namespace: {{ include "vm.namespace" . }}
spec:
  {{- with $ingress.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with $ingress.tls }}
  tls: {{ toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range $ingress.hosts }}
    - host: {{ tpl .name $ }}
      http:
        paths:
          - path: {{ .path }}
            {{- with $ingress.pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ $serviceName }}
                port: {{ include "vm.ingress.port" . | nindent 18 }}
    {{- end }}
{{- end }}
