{{- $app := .Values.vmstorage }}
{{- $service := $app.service }}
{{- if $app.enabled -}}
{{- $ctx := dict "helm" . "extraLabels" $service.labels "appKey" "vmstorage" }}
apiVersion: v1
kind: Service
metadata:
  {{- with $service.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  labels: {{ include "victoria-metrics.vmstorage.labels" $ctx | nindent 4 }}
  name: {{ include "vm.plain.fullname" $ctx }}
  namespace: {{ include "vm.namespace" . }}
spec:
  clusterIP: None
  type: ClusterIP
  {{- with $service.healthCheckNodePort }}
  healthCheckNodePort: {{ . }}
  {{- end }}
  {{- with $service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with $service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with $service.ipFamilies }}
  ipFamilies: {{ toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ $service.servicePort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ $service.vmselectPort }}
      targetPort: vmselect
      protocol: TCP
      name: vmselect
    - port: {{ $service.vminsertPort }}
      targetPort: vminsert
      protocol: TCP
      name: vminsert
    {{- range $service.extraPorts }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: TCP
      targetPort: {{ .targetPort }}
    {{- end }}
  selector: {{ include "victoria-metrics.vmstorage.matchLabels" (omit $ctx "extraLabels") | nindent 4 }}
{{- end -}}
