{{- $app := .Values.vmstorage }}
{{- $serviceMonitor := $app.serviceMonitor }}
{{- if and $app.enabled $serviceMonitor.enabled -}}
{{- $ctx := dict "helm" . "extraLabels" $serviceMonitor.extraLabels "appKey" "vmstorage" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  {{- with $serviceMonitor.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  labels: {{ include "victoria-metrics.vmstorage.labels" $ctx | nindent 4 }}
  name: {{ include "vm.plain.fullname" $ctx }}
  {{- with $serviceMonitor.namespace }}
  namespace: {{ . }}
  {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ include "vm.namespace" . }}
  selector:
    matchLabels: {{ include "victoria-metrics.vmstorage.matchLabels" (omit $ctx "extraLabels") | nindent 6 }} 
  endpoints:
    - port: http
      {{- with $serviceMonitor.basicAuth }}
      basicAuth: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $serviceMonitor.scheme }}
      scheme: {{ . }}
      {{- end }}
      {{- with $serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with $serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with $serviceMonitor.tlsConfig }}
      tlsConfig: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $serviceMonitor.relabelings }}
      relabelings: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $serviceMonitor.metricRelabelings }}
      metricRelabelings: {{ toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
