{{ if and .Values.read.global.vmauth.enabled (index .Values "victoria-metrics-k8s-stack" "grafana" "enabled") }}
{{- $url := (printf "%s/select/0/prometheus/" (include "vm.url" .)) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vm.fullname" . }}-grafana-ds
  namespace: {{ include "vm.namespace" . }}
  labels: {{ include "victoria-metrics-distributed.labels" . | nindent 4 }}
    {{ index .Values "victoria-metrics-k8s-stack" "grafana" "sidecar" "datasources" "label" }}: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: VictoriaMetrics
      type: prometheus
      url: {{ $url }}
      access: proxy
      isDefault: true
      jsonData: {}
{{- end }}

