{{- $app := .Values.vmcluster }}
{{- if $app.enabled }}
{{- $ctx := dict "helm" . "appKey" "vmcluster" }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  {{- with $app.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end  }}
  name: {{ include "vm.fullname" $ctx }}
  namespace: {{ include "vm.namespace" . }}
  labels: {{ include "victoria-metrics-k8s-stack.labels" . | nindent 4 }}
spec: {{ include "vm.cluster.spec" . | nindent 2 }}
{{- end }}
