{{- if .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "vm-operator.fullname" . }}
  {{- $ctx := dict "helm" . "extraLabels" .Values.extraLabels }}
  labels: {{ include "vm-operator.labels" $ctx | nindent 4 }}
  {{- with .Values.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "vm-operator.serviceAccountName" . }}
  namespace: {{ include "vm.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "vm-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
