{{- $service := .Values.service }}
{{- $ctx := dict "helm" . "extraLabels" .Values.extraLabels }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "vm.namespace" . }}
  {{- with $service.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  labels: {{ include "vm-operator.labels" $ctx | nindent 4 }}
  name: {{ include "vm.fullname" . }}
spec:
  {{- with $service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with $service.externalIPs }}
  externalIPs: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with $service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with $service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{ toYaml . | nindent 4 }}
  {{- end }}
  type: {{ $service.type }}
  {{- with $service.healthCheckNodePort }}
  healthCheckNodePort: {{ . }}
  {{- end }}
  {{- with $service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with $service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with $service.ipFamilies }}
  ipFamilies: {{ toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.servicePort }}
      targetPort: http
      protocol: TCP
    - name: webhook
      port: {{ .Values.service.webhookPort }}
      targetPort: webhook
  selector: {{ include "vm-operator.selectorLabels" . | nindent 4 }}
