{{- if and .Values.server.scrape.enabled (eq .Values.server.scrape.configMap "") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "victoria-metrics.server.scrape.configname" . }}
  namespace: {{ include "vm.namespace" . }}
  labels: {{ include "victoria-metrics.server.labels" . | nindent 4 }}
data:
  {{- $config := .Values.server.scrape.config }}
  {{- with .Values.server.scrape.extraScrapeConfigs }}
    {{- if hasKey "scrape_configs" $config }}
      {{- $_ := set $config (concat $config.scrape_configs .) }}
    {{- end }}
  {{- end }}
  scrape.yml: |{{ toYaml $config }}
{{- end }}
