{{- $app := .Values.server }}
{{- $service := $app.service }}
{{- if $app.enabled -}}
{{- $ctx := dict "helm" . "extraLabels" $service.labels }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "vm.namespace" $ctx }}
  {{- with $service.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  labels: {{ include "victoria-metrics.server.labels" $ctx | nindent 4 }}
  name: {{ include "vm.server.fullname" $ctx }}
spec:
  {{- $clusterIP := $service.clusterIP }}
  {{- if and (not $clusterIP) $app.statefulSet.enabled }}
    {{- $clusterIP = "None" }}
  {{- end }}
  {{- with $clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with $service.externalIPs }}
  externalIPs: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with $service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with $service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- $type := $service.type }}
  {{- if and (not $type) $app.statefulSet.enabled }}
    {{- $type = "ClusterIP" }}
  {{- end }}
  type: {{ $type }}
  {{- with $service.healthCheckNodePort }}
  healthCheckNodePort: {{ . }}
  {{- end }}
  {{- with $service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with $service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with $service.ipFamilies }}
  ipFamilies: {{ toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: http
      port: {{ $service.servicePort }}
      protocol: TCP
      targetPort: http
      {{- with $service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
    {{- with $app.extraArgs.graphiteListenAddr }}
    - name: graphite-tcp
      protocol: TCP
      port: {{ include "vm.port.from.flag" (dict "flag" .) }}
      targetPort: graphite-tcp
    - name: graphite-udp
      protocol: UDP
      port: {{ include "vm.port.from.flag" (dict "flag" .) }}
      targetPort: graphite-udp
    {{- end }}
    {{- with $app.extraArgs.influxListenAddr }}
    - name: influx-tcp
      protocol: TCP
      port: {{ include "vm.port.from.flag" (dict "flag" .) }}
      targetPort: influx-tcp
    - name: influx-udp
      protocol: UDP
      port: {{ include "vm.port.from.flag" (dict "flag" .) }}
      targetPort: influx-udp
    {{- end }}
    {{- with $app.extraArgs.opentsdbHTTPListenAddr }}
    - name: opentsdbhttp
      port: {{ include "vm.port.from.flag" (dict "flag" .) }}
      targetPort: opentsdbhttp
    {{- end }}
    {{- with $app.extraArgs.opentsdbListenAddr }}
    - name: opentsdb-udp
      protocol: UDP
      port: {{ include "vm.port.from.flag" (dict "flag" .) }}
      targetPort: opentsdb-udp
    - name: opentsdb-tcp
      protocol: TCP
      port: {{ include "vm.port.from.flag" (dict "flag" .) }}
      targetPort: opentsdb-tcp
    {{- end }}
  selector: {{ include "victoria-metrics.server.matchLabels" (omit $ctx "extraLabels") | nindent 4 }}
{{- end }}
