{{- $sa := .Values.serviceAccount }}
{{- if $sa.create }}
{{- $ctx := dict "helm" . "extraLabels" $sa.extraLabels }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {{- include "victoria-metrics.common.metaLabels" $ctx | nindent 4 }}
  {{- with $sa.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "vm.sa.name" $ctx }}
  namespace: {{ include "vm.namespace" $ctx }}
{{- end }}
